### ISSUE TITLE
Error compiling on Debian 8.6

### ISSUE THREAD

**Issue by FlamesRunner** [lightsey/mod_suphp#1]
Hello,

I was compiling your suPHP fork, and I experienced the following error while compiling it:

    checking how to hardcode library paths into programs... immediate
    ./configure: line 15296: syntax error near unexpected token `,optional'
    ./configure: line 15296: `AX_CXX_COMPILE_STDCXX_11(,optional)'

What seems to be the issue?

Thanks.

**Comment by lightsey** [comment]
You'll need to install the autoconf-archive package in addition to the standard build-essential packages to regenerate the autoconf and automake files on Debian. The AX_CXX_COMPILE_STDCXX_11 m4 macro is from that package.

I'll add some instructions to the repo about building from source.

**Comment by FlamesRunner** [comment]
That's odd. I had installed the package and done all those steps before compiling, yet it still occurred. 

I downgraded by a minor version and it worked.

Thanks for the help!
