### ISSUE TITLE
Variable substitution in docroot eats a char

### ISSUE THREAD

**Issue by maswan** [lightsey/mod_suphp#3]
When configuring docroot, I ran into an issue which seems to be that the variable resolution eats the next character after the pattern.

What I expected to work: ${HOME}/public_html
What actually worked: ${HOME}Q/public_html

Compiled on Ubuntu 18.04 from current git as of this issue.

**Comment by lightsey** [comment]
Very odd, thanks for reporting this bug.

I'll try to reproduce it this weekend and put together a fix with unit test.

**Comment by lightsey** [comment]
Ended up as a simple mistake in the way the original code was skipping to the end of the variable. Fixed in the master branch now.
